const keywords = [
  "Các Dân Tộc Việt Nam",
  "Dân Tộc Học – Lý Thuyết và Thực Tiễn",
  "Văn Hóa Các Dân Tộc Thiểu Số Việt Nam",
  "Dân Tộc Và Sự Phát Triển Ở Tây Nguyên",
  "Dân Tộc Học So Sánh",
  "Người H'Mông Ở Việt Nam",
  "Biến Đổi Văn Hóa Các Dân Tộc",
  "Chính Sách Dân Tộc Ở Việt Nam Hiện Nay",
  "Người Dao Ở Vùng Cao",
  "Phong Tục Tập Quán Các Dân Tộc Phía Bắc",
  "Thiền Và Nghệ Thuật Sống",
  "Thiền Trong Đời Sống Hằng Ngày",
  "Hơi Thở Chánh Niệm",
  "Thiền Vipassana",
  "Sống Thiền",
  "Bước Chân An Lạc",
  "Giận – Thiền Sư Thích Nhất Hạnh",
  "Trái Tim Thiền Tập",
  "Thiền Và Não Bộ",
  "Thiền Sư Và Em Bé Năm Tuổi",
  "Cẩm Nang Y Học Cổ Truyền Trung Quốc",
  "Bách Khoa Y Học Cổ Truyền",
  "Châm Cứu Học Thực Hành",
  "Lý Luận Cơ Bản Y Học Cổ Truyền",
  "Dược Liệu Trung Hoa",
  "Phương Pháp Bấm Huyệt",
  "Chẩn Đoán Đông Y",
  "Tự Chữa Bệnh Bằng Y Học Cổ Truyền",
  "Dưỡng Sinh Theo Y Học Phương Đông",
  "Thiền Và Đông Y",
  "Địa Chí Lào Cai",
  "Du Lịch Lào Cai",
  "Con Người Và Văn Hóa Lào Cai",
  "Phong Tục Lào Cai",
  "Vùng Cao Lào Cai – Giao Lưu Văn Hóa",
  "Đặc Sản Lào Cai",
  "Lào Cai – Hành Trình Khám Phá",
  "Các Dân Tộc Ở Lào Cai",
  "Lào Cai: Hành Trình Phát Triển",
  "Lào Cai – Di Sản Và Hội Nhập",
  "Khởi Nghiệp Tinh Gọn",
  "Chiến Lược Cạnh Tranh",
  "Quản Trị Doanh Nghiệp Nhỏ Và Vừa",
  "Tư Duy Doanh Nhân",
  "CEO 4.0",
  "Bí Quyết Xây Dựng Doanh Nghiệp Vững Bền",
  "Phát Triển Doanh Nghiệp Trong Thời Kỳ Khủng Hoảng",
  "Công Ty Khởi Nghiệp Triệu Đô",
  "Tăng Tốc Doanh Nghiệp Với OKR",
  "Tái Cấu Trúc Doanh Nghiệp",
  "Canh Tác Hữu Cơ",
  "Bảo Tồn Giống Bản Địa",
  "Kỹ Thuật Sinh Thái Trong Nông Nghiệp",
  "Phát Triển Nông Nghiệp Bền Vững",
  "Giữ Gìn Đa Dạng Sinh Học",
  "Nông Nghiệp Tuần Hoàn",
  "Nông Nghiệp Sinh Thái",
  "Hệ Thống Lương Thực Bền Vững",
  "Cẩm Nang Nông Nghiệp Bền Vững",
  "Công Nghệ Sinh Học Trong Nông Nghiệp",
  "Kỹ Thuật Nuôi Cá Lóc",
  "Nuôi Tôm Công Nghiệp",
  "Nuôi Cá Tra Và Ba Sa",
  "Kỹ Thuật Nuôi Lươn",
  "Chế Biến Thủy Sản",
  "Quản Lý Ao Nuôi",
  "Nuôi Thủy Sản Thân Thiện Môi Trường",
  "Phòng Trị Bệnh Cá",
  "Sổ Tay Kỹ Thuật Nuôi Tôm",
  "Cẩm Nang Nuôi Trồng Thủy Sản",
  "Chẩn Đoán Và Điều Trị Bệnh Trên Chó Mèo",
  "Dược Lý Thú Y",
  "Bệnh Truyền Nhiễm Ở Gia Súc",
  "Kỹ Thuật Gây Mê Trong Thú Y",
  "Giải Phẫu Học Thú Y",
  "Sinh Lý Học Thú Y",
  "Sổ Tay Thú Y",
  "Thực Hành Thú Y Hiện Đại",
  "Vaccine Và Miễn Dịch Trong Thú Y",
  "Nuôi Và Chăm Sóc Vật Nuôi",
  "Luật Lao Động Việt Nam (mới nhất)",
  "Bình Luận Bộ Luật Lao Động",
  "Chính Sách Về Hợp Đồng Lao Động",
  "Luật Bảo Hiểm Xã Hội",
  "Nghị Định Hướng Dẫn Luật Lao Động",
  "Tranh Chấp Lao Động Và Giải Quyết",
  "Quyền Và Nghĩa Vụ Người Lao Động",
  "Luật Công Đoàn",
  "Sổ Tay Luật Lao Động",
  "Giải Đáp Tình Huống Pháp Lý Về Lao Động",
  "Đông Nam Á – Văn Hóa Và Lịch Sử",
  "ASEAN – Những Chặng Đường Phát Triển",
  "Địa Chính Trị Đông Nam Á",
  "Kinh Tế Đông Nam Á",
  "Quan Hệ Việt Nam – ASEAN",
  "Tôn Giáo Đông Nam Á",
  "Đông Nam Á – Lược Sử",
  "Văn Hóa Các Nước Đông Nam Á",
  "Chính Trị Khu Vực Đông Nam Á",
  "Các Quốc Gia ASEAN Hiện Đại",
];
module.exports = { keywords };
